notifications:
  slack:
    secure: j3t/N/O0YD1BZsiihdrw5yYLFtyYZgVPkxcCIr0yWEYRhk1OWw2RS/UcM+fjQjaRZMhSn+k6vFW5YXNMEPEDvVbuTt75Sj9Gy3YeSYmO6b9ZIUBDDkamBMMx1c2YUxZTZaL7gRaLF8H9+xz9MIMvsGeJAjSs0H8QtOMscWEO6n+Uko/HX/Sw/p/EpdnWBj6CBu+WKutmRM/4QVRVe+kJirLrx8Hux7ejCnxskdfbh/i/beq6Oy9PQEsBLLn2+kGWxXb2lurCdH/eQtnshIJLHO5ee0XDEyp+H1QFXKQnu//QIAAW5QcEU6hM0aP1j37n5J/uRsARf86e6iYSIvP3esvuKGBLnb9iqR/qx/aekqc8fIXmi8a5Slgor4m2W2RxHlTKijdwwzIzX1BFOV3hxJ3ZmeOs8j95OpesQfHS4tAxhbLowJvZT38pBm3rOwTWeotz1CE81Zs2ycnjVI93a5xG9VteXh4xOfrHgBqkOgaohrl9wQknc7x0W5xGe1ycf6o6pLln6nFs9MqgXjFH7XTOajQL+mChukA7iRFznnE97xMN4rrKiRzluZ4C8A6z0GXWyYuI2FQdg5mj8zh2S4NkuJvud3vHanCDHjVkRDVv5AIi7qMGgt2c1Cv/lqGZhwT1nXpSpgF5TsOtKOHfa54wzqnJiEucWacuwdQziHc=
  email:
    recipients:
    - mark.mcewen@capita.com
    on_success: never
    on_failure: always
services:
- docker
env:
  global:
  - FLASK_APP=todo_app/app FLASK_ENV=development
  - secure: EXav8MfB+psh+Fzm0gUjFWpR02490CB0lCGpReR2knuESkaf9nmy+R8obr31OlQHB0oX7ixocG8/KNpF7d9GiZtYt/RiO+1gAAWT0YOA/A3LQ5lnYA2I04h3JUWeUBK1KJwBdK88ca4i+mfJKYKoIeRliwkvuGTOmgQlQ19zwjej6NIFiA2taLbs2TZ4ZW9w0rw8WRx1W5VDJ4pjqCjXS9YBVGqqrWgh9/kXjkUc1RYyGBaTexi24vPG9JPRwyP/qtwoB19ThqCMiyi+HxA/9p50Jw7BAJIFYKBw8Saq0OF0VxCs3G8XT6y4AjUc77mD1d8UQ5Oovn8iLjISk5vy9R03gIK/nVLaSxqojmEzrUrdB9OTOJrUhCpc8Lq6oOTZfZnLLtlhDbkg+8mpJvqEwPxSMBEUDuVbDEsbcI2YcCgB/TxwOieo+67rqzq6sEtX5JxwQhP1ZiJ4E+srbhvZkGtI+pJyELs/1LZb42bn+cNWa4znKDvJcpireqQ1h5vel92rB60Axg/t3Mgqg0P3Jqg55Bf5zi4u3gqLaWESjc0n8NdavDgQ+iLVC7Dtdh2nPQ2k7pGHeiA/isxneo/nF9yCuvTqJvCjFsboAv1HQwX89SHiQGvqZV4nJDHTaH7evwMdb6gvuDw0BjeOhqumoDf0c09ZfO495dYbcI/oeiE=
  - secure: NqG5WvbeIj0JbVrJMbepKZQwHEl2pJSZvYIckDTDy528rGf6ICdmp4PuhwyPboCDYO9/VxySXgaXrGjE3Hc/E9teWqiJwgcnB/YLpVBBgjcEfxOUU+KTUGlx4VJ6dIaQf1I6EBxe8Qw3mWP3gINp89JlO1iqwwKhXPkY2YpMIRZgyHLHcNAiIrRGg2If481XfRDZkVt+k7UfVTYOKygvUncCLv8v02oZ9kWeX61CIkLgqAZYhI8j9bYA0tA+6koHSSZ1IgjvgsmW2CMfjrqPVOwXxnyqM8dFet82BeQtGeWIsYBVtZtgRFCdvpqx7+nQw/addyRVVM1SOir78ZW6mJ2beGT3V5eRAvGNCgGgZDJ4mSIWFrg3Z6EPT3G+zeAzg6dee+kByO++Nx+4cMYIOx9ZUMJC9eOlvrGM44tccvV3HkJ4JVF+vD8gXzDKWh6YaiHPe3iOKy5e5akcWs4WZAvYdfWygJ4bddfCjbO3xMGLSpGQdTiiwiySF22DvyaaBgZcYH6zyYb38KygM9oCMVjeMfDNi8m6qKj6lPNmk1jVxPLq3d30n5biyC2epakMK0waky7JE2h4AYq2Y8cpaXeq9w0gQjtt4QCjTTw56xrk+fRJYcJp2KnCr//GlL5NCdvxG8uu2DqXX6Aeu4Pj+6XPiFUeMQbihrPlDJ8O1zk=
  - DOCKER_USERNAME=markmcdevops
  - MONGO_PREFIX=mongodb://
  - LOGIN_DISABLED=True
jobs:
  include:
  - stage: Build docker images
    before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    script:
    - docker build --target production --tag $DOCKER_USERNAME/todo-app:latest .
    - docker push $DOCKER_USERNAME/todo-app:latest
    deploy:
      provider: script
      script:
      - curl -dH -X POST '$AZURE_WEBHOOK'
      on:
        all_branches: true
  - stage: Test
    script:
    - docker build --target test --tag $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT-test .
    - docker build --target test_e2e --tag $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT-test_e2e .
    - docker run -e SECRET_KEY -e USER_NAME -e PASSWORD -e MONGO_URL -e MONGO_PREFIX
      -e DEFAULT_DATABASE -e LOGIN_DISABLED --mount type=bind,source="$(pwd)"/todo_app,target=/project/todo_app
      $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT-test
    - docker run -e SECRET_KEY -e USER_NAME -e PASSWORD -e MONGO_URL -e MONGO_PREFIX
      -e DEFAULT_DATABASE -e LOGIN_DISABLED --mount type=bind,source="$(pwd)"/todo_app,target=/project/todo_app
      $DOCKER_USERNAME/todo-app:$TRAVIS_COMMIT-test_e2e
